version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
        - ${MYSQL_PORT}:3306
    volumes:
        - mysqldb:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
        MYSQL_DATABASE: "${MYSQL_DATABASE}"
        MYSQL_USER: "${MYSQL_USER}"
        MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - tmob
    restart: always
  cache:
    container_name: memcached
    image: "memcached:latest"
    ports:
        - ${MEMCACHED_PORT}:11211
    networks:
      - tmob

volumes:
  mysqldb:

networks:
  tmob: