# Generated by Django 2.2.28 on 2022-12-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='_url',
            field=models.CharField(max_length=250),
        ),
    ]
